/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2021-08-26 11:38:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <section class=\"mb-5\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("              <div class=\"row\">\n");
      out.write("                <div class=\"col-md-6 mb-5\">\n");
      out.write("                  <h1 class=\"display-4\">Contact Us</h1>\n");
      out.write("                  <p class=\"lead text-secondary\">A free bootstrap template by <a href=\"https://uicookies.com/\" target=\"_blank\">uicookies.com</a></p>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <section class=\"probootstrap-services\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("              <div class=\"row no-gutters\">\n");
      out.write("                <div class=\"col-md-3 pb-5 probootstrap-aside-stretch-left probootstrap-inside\">\n");
      out.write("                  <div class=\"mb-3 pt-5\">\n");
      out.write("                    <h2 class=\"h6\">Contact</h2>\n");
      out.write("                    <ul class=\"list-unstyled probootstrap-light mb-4\">\n");
      out.write("                      <li class=\"active\"><a href=\"#\">Contact</a></li>\n");
      out.write("                      <li><a href=\"#\">More Link</a></li>\n");
      out.write("                      <li><a href=\"#\">Another Link</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-9 pl-md-5 pb-5 pl-0 probootstrap-inside\">\n");
      out.write("                  <h1 class=\"mt-4 mb-4\">Get In Touch</h1>\n");
      out.write("                  <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-12\">\n");
      out.write("                      <form action=\"\" method=\"post\" class=\"probootstrap-form\">\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                          <label for=\"name\" class=\"sr-only\">Name</label>\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"name\" placeholder=\"Enter your name\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                          <label for=\"email\" class=\"sr-only\">Email</label>\n");
      out.write("                          <input type=\"text\" class=\"form-control\" id=\"email\" placeholder=\"Enter your email\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                          <label for=\"message\" class=\"sr-only\">Message</label>\n");
      out.write("                          <textarea name=\"message\" id=\"message\" cols=\"30\" rows=\"10\" class=\"form-control\" placeholder=\"Write your message\"></textarea>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                          <input type=\"submit\" class=\"btn btn-primary\" value=\"Send Message\">\n");
      out.write("                        </div>\n");
      out.write("                      </form>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <section class=\"probootstrap-subscribe\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("              <div class=\"row mb-5\">\n");
      out.write("                <div class=\"col-md-12\">\n");
      out.write("                  <h2 class=\"h1 text-white\">Subscribe Newsletter</h2>\n");
      out.write("                  <p class=\"lead text-white\">Far far away, behind the word mountains, far from the countries Vokalia.</p>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <form action=\"#\" method=\"post\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                  <div class=\"col-md-4\">\n");
      out.write("                    <input type=\"text\" class=\"form-control\" placeholder=\"Name\">    \n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-md-4 mb-md-0 mb-3\">\n");
      out.write("                    <input type=\"text\" class=\"form-control\" placeholder=\"Email\">\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-md-4\">\n");
      out.write("                    <input type=\"submit\" value=\"Subscribe\" class=\"btn btn-primary btn-block\">\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        \n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
