/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2021-08-26 11:30:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/C:/Users/nguye/Documents/GitHub/DoAnNganhCNTT/target/HospitalManager-1.0-SNAPSHOT/WEB-INF/lib/spring-webmvc-5.2.2.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1575337710000L));
    _jspx_dependants.put("jar:file:/C:/Users/nguye/Documents/GitHub/DoAnNganhCNTT/target/HospitalManager-1.0-SNAPSHOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("jar:file:/C:/Users/nguye/Documents/GitHub/DoAnNganhCNTT/target/HospitalManager-1.0-SNAPSHOT/WEB-INF/lib/tiles-jsp-3.0.8.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1506780484000L));
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-3.0.8.jar", Long.valueOf(1628649325864L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.2.RELEASE.jar", Long.valueOf(1628043627539L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1628043630998L));
    _jspx_dependants.put("jar:file:/C:/Users/nguye/Documents/GitHub/DoAnNganhCNTT/target/HospitalManager-1.0-SNAPSHOT/WEB-INF/lib/spring-webmvc-5.2.2.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1575337710000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"probootstrap-footer\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"row mb-5\">\n");
      out.write("        <div class=\"col-md-3\">\n");
      out.write("          <h3 class=\"heading\">Latest Blog</h3>\n");
      out.write("          <ul class=\"list-unstyled probootstrap-footer-recent-post\">\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\"><span class=\"date\">November 15, 2017</span> The practice of medicine is a lot like parenting </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\"><span class=\"date\">November 15, 2017</span>Physicians: Want to overcome burnout? Start studying business. </a>\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-3\">\n");
      out.write("          <h3 class=\"heading\">Head Office</h3>\n");
      out.write("          <p class=\"mb-5\">98 West 21th Street, Suite 721 New York NY 10016</p>\n");
      out.write("          <h3 class=\"heading text-white\">Open</h3> \n");
      out.write("          <p>\n");
      out.write("            Mon-Fri 7:30-18:00 <br>\n");
      out.write("            Sat 7:30-18:00 <br>\n");
      out.write("            Sun 7:30-18:00\n");
      out.write("          </p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-3\">\n");
      out.write("          <h3 class=\"heading\">Quick Links</h3>\n");
      out.write("          <ul class=\"list-unstyled probootstrap-footer-links\">\n");
      out.write("            <li><a href=\"#\">Home</a></li>\n");
      out.write("            <li><a href=\"#\">Department</a></li>\n");
      out.write("            <li><a href=\"#\">About</a></li>\n");
      out.write("            <li><a href=\"#\">Contact</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-3\">\n");
      out.write("          <h3 class=\"heading\">Follow us</h3>\n");
      out.write("          <ul class=\"probootstrap-footer-social\">\n");
      out.write("            <li><a href=\"#\"><span class=\"icon-twitter\"></span></a></li>\n");
      out.write("            <li><a href=\"#\"><span class=\"icon-facebook\"></span></a></li>\n");
      out.write("            <li><a href=\"#\"><span class=\"icon-linkedin\"></span></a></li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <!-- END row -->\n");
      out.write("      <div class=\"row probootstrap-copyright\">\n");
      out.write("        <div class=\"col-md-12\">\n");
      out.write("          <p><small>&copy; 2017 <a href=\"https://uicookies.com/\" target=\"_blank\">uiCookies Health</a>. All Rights Reserved. Designed &amp; Developed by <a href=\"https://uicookies.com/\" target=\"_blank\">uicookies.com</a> (please don't remove credit, see <a href=\"https://uicookies.com/license/\" target=\"_blank\">license</a>)  <br> Demo Images <a href=\"https://pexels.com/\">Pexels</a> </small></p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("</footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
